name: Terraform Plan
on: push
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}

jobs:
  terraform_plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Plan
      run: |
        terraform init
        terraform fmt -recursive
        terraform validate
        terraform plan
  
